import Script from 'next/script';

export default function Head() {
  return (
    <head>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/* 네이버 지도 */}
      <Script type="text/javascript" src="http://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=yDj1zz6s7PIruaIuI3kU" />
      <Script type="text/javascript" src="https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=yDj1zz6s7PIruaIuI3kU&submodules=geocoder" />
    </head>
  )
}
